language: node_js
node_js:
    - "stable"
script:
    - npm run int:test
cache: 
directories:
    - "node_modules"
addons:
apt:
    update: true    
after_success:
    - npm run lint
    - npm run coveralls
services:
    - postgresql
notifications:
    email: false
